/* Generated by AN DISI Unibo */ 
package it.unibo.parkingservicegui3

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingservicegui3 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var SLOTNUM = -1
				var TOKENID = -1
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("	parkingservicegui3 (client mock)  STARTS")
					}
					 transition( edgeName="goto",targetState="requestToEnter", cond=doswitch() )
				}	 
				state("requestToEnter") { //this:State
					action { //it:State
						println("	client3 requestToenter ")
						request("reqenter", "reqenter(client)" ,"parkingmanagerservice" )  
					}
					 transition(edgeName="t010",targetState="enterthecar",cond=whenReply("enter"))
				}	 
				state("enterthecar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("enter(SLOTNUM)"), Term.createTerm("enter(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SLOTNUM = payloadArg(0 ).toInt()  
								println("	client3 receives SLOTNUM = $SLOTNUM ")
						}
					}
					 transition( edgeName="goto",targetState="movethecartoindoor", cond=doswitch() )
				}	 
				state("movethecartoindoor") { //this:State
					action { //it:State
						println("	client3 moving the car in the INDOOR and press CARENTER ")
						request("carenter", "carenter($SLOTNUM)" ,"parkingmanagerservice" )  
					}
					 transition(edgeName="t011",targetState="afterreceipt",cond=whenReply("receipt"))
				}	 
				state("afterreceipt") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("receipt(TOKENID)"), Term.createTerm("receipt(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TOKENID = payloadArg(0).toInt() 
								println("	client3 receives TOKENID = $TOKENID ")
						}
						println("$name in ${currentState.stateName} | $currentMsg")
						stateTimer = TimerActor("timer_afterreceipt", 
							scope, context!!, "local_tout_parkingservicegui3_afterreceipt", 10000.toLong() )
					}
					 transition(edgeName="t012",targetState="reqpickup",cond=whenTimeout("local_tout_parkingservicegui3_afterreceipt"))   
				}	 
				state("reqpickup") { //this:State
					action { //it:State
						println("	client3 wants to pickup TOKENID = $TOKENID ")
						request("pickup", "pickup($TOKENID)" ,"parkingmanagerservice" )  
					}
					 transition(edgeName="t013",targetState="waitForCarOutDoorArrival",cond=whenReply("pickupAccepted"))
				}	 
				state("waitForCarOutDoorArrival") { //this:State
					action { //it:State
					}
					 transition(edgeName="t014",targetState="pickup",cond=whenEvent("caroutdoorarrival"))
				}	 
				state("pickup") { //this:State
					action { //it:State
						println("	client3 pickup TOKENID = $TOKENID ")
						delay(2000) 
						emit("carwithdrawn", "cw(bye)" ) 
					}
				}	 
			}
		}
}
